services:
  vaultwarden:
    image: vaultwarden/server:latest
    restart: always
    volumes:
      - ./data:/data
    env_file:
      - .env
    environment:
      - DOMAIN=https://vault.qqey.net
      - WEBSOCKET_ENABLED=true

  cloudflared:
    image: cloudflare/cloudflared:latest
    user: root
    restart: always
    command: tunnel run --token $CLOUDFLARED_TOKEN
