services:
  vaultwarden:
    image: vaultwarden/server:latest
    restart: always
    volumes:
      - ./data:/data
    ports:
      - "8838:80"
    environment:
      - DOMAIN=https://vault.qqey.net
      - WEBSOCKET_ENABLED=true
      - ADMIN_TOKEN=eXZkHMd0oHz05KuxT7JkeXZkHMd0oHz05KuxT7Jk
