services:
  openldap:
    image: osixia/openldap
    restart: always
    container_name: openldap
    environment:
      LDAP_ORGANISATION: "qqey.net"
      LDAP_DOMAIN: "qqey.net"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_READONLY_USER: "true"
      LDAP_READONLY_USER_USERNAME: "readonly"
      LDAP_READONLY_USER_PASSWORD: "readonly_password"
      LDAP_TLS_VERIFY_CLIENT: "never"
    ports:
      - 389:389
      - 636:636
    volumes:
      - ./data:/var/lib/ldap
      - ./config:/etc/ldap/slapd.d
    networks:
      - local

  phpldapadmin:
    image: osixia/phpldapadmin
    container_name: phpldapadmin
    restart: always
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    ports:
      - "6443:443"
    networks:
      - local
networks:
  local:
    driver: bridge
