services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    tty: true
    stdin_open: true
    volumes:
      - ./certs/keycloak.crt:/etc/x509/https/keycloak.crt
      - ./certs/keycloak.key:/etc/x509/https/keycloak.key
    ports:
        - 8849:8443
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME: localhost
      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/keycloak.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/keycloak.key
    command:
      - start
