services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    tty: true
    stdin_open: true
    ports:
        - 8849:8443
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME: localhost
    command:
      - start
