services:
  mail:
    container_name: mail
    image: stalwartlabs/mail-server:latest
    volumes:
      - ./volumes/stalwart-mail:/opt/stalwart-mail
    ports:
      - "8080:8080"
      - "25:25"
      - "587:587"
      - "465:465"
      - "8686:8686"
      - "143:143"
      - "993:993"
      - "4190:4190"
